# Generated by Django 3.1.1 on 2020-09-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPost',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=20)),
                ('post', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
