# Generated by Django 3.1.1 on 2020-09-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypost',
            old_name='id',
            new_name='uid',
        ),
    ]
