# Generated by Django 3.1.1 on 2020-09-12 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200912_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypost',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 12, 16, 12, 0, 197852, tzinfo=utc)),
        ),
    ]
