# Generated by Django 3.1.1 on 2020-09-12 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200912_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
