# Generated by Django 3.1.1 on 2020-09-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200926_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='historypost',
            name='likes',
        ),
    ]
