# Generated by Django 3.1.1 on 2020-09-12 18:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200912_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypost',
            name='post',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
