# Generated by Django 3.1.1 on 2020-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200912_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypost',
            name='slug',
        ),
        migrations.AddField(
            model_name='historypost',
            name='uid',
            field=models.BigAutoField(default='0', primary_key=True, serialize=False, unique=True),
        ),
    ]
