# Generated by Django 3.1.1 on 2020-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200913_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypost',
            name='uid',
            field=models.IntegerField(default='0', primary_key=True, serialize=False, unique=True),
        ),
    ]
