# Generated by Django 3.1.1 on 2020-09-13 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200913_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
